# Generated by Django 2.1 on 2020-06-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=128)),
                ('job_state', models.BinaryField()),
                ('description', models.TextField(blank=True)),
                ('next_run_time', models.DateTimeField()),
                ('gmt_update', models.DateTimeField(auto_now=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('next_run_time',),
            },
        ),
        migrations.CreateModel(
            name='JobExecHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('status', models.CharField(choices=[['Max instances reached!', 'Max instances reached!'], ['Missed!', 'Missed!'], ['Error!', 'Error!'], ['Executed', 'Executed']], max_length=50)),
                ('job_instance_id', models.CharField(max_length=64)),
                ('start_tm', models.DateTimeField()),
                ('end_tm', models.DateTimeField()),
                ('duration', models.IntegerField(default=-1)),
                ('trace_message', models.TextField(blank=True, verbose_name='追踪日志')),
                ('gmt_update', models.DateTimeField(auto_now=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_apscheduler_ng.DjangoJob')),
            ],
            options={
                'ordering': ('-start_tm',),
            },
        ),
    ]
