# Generated by Django 2.1 on 2020-06-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler_ng', '0002_auto_20200604_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobexechistory',
            old_name='job_id',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='jobexechistory',
            name='start_tm',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
