# Generated by Django 2.1 on 2020-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler_ng', '0003_auto_20200604_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexechistory',
            name='status',
            field=models.CharField(choices=[[32768, 'Running'], [4096, 'Executed'], [8192, 'Error!'], [16384, 'Missed!'], [65536, 'Max instances reached!']], max_length=50),
        ),
    ]
