# Generated by Django 2.1 on 2020-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler_ng', '0004_auto_20200604_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexechistory',
            name='job_instance_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='jobexechistory',
            name='status',
            field=models.CharField(choices=[['32768', 'Running'], ['4096', 'Success'], ['8192', 'Error!'], ['16384', 'Missed!'], ['65536', 'Max instances reached!']], max_length=50),
        ),
    ]
