# Generated by Django 2.1 on 2020-06-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler_ng', '0005_auto_20200604_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexechistory',
            name='gmt_created',
        ),
        migrations.RemoveField(
            model_name='jobexechistory',
            name='gmt_update',
        ),
        migrations.AlterField(
            model_name='jobexechistory',
            name='end_tm',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
