# Generated by Django 2.1 on 2020-06-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler_ng', '0006_auto_20200604_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexechistory',
            name='duration',
        ),
    ]
